"""
LangChain RAG Pipeline for Healthcare Medical Q&A.

Chain: embed query → retrieve top-5 FAISS chunks → inject context
       into prompt → generate answer via flan-t5-base → append disclaimer.

Usage:
    from src.rag.pipeline import build_rag_pipeline, answer

    pipeline = build_rag_pipeline()
    result = answer("What are the symptoms of diabetes?", pipeline=pipeline)
"""

import os
import pickle
from pathlib import Path

import faiss
import numpy as np
from sentence_transformers import SentenceTransformer
from transformers import pipeline as hf_pipeline


# ── Constants ────────────────────────────────────────────────────────────────

DISCLAIMER = (
    "\n\n⚠️ MEDICAL DISCLAIMER: This response is generated by an AI system "
    "for educational and informational purposes only. It is NOT a substitute "
    "for professional medical advice, diagnosis, or treatment. Always consult "
    "a qualified healthcare provider for medical decisions."
)

DEFAULT_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
DEFAULT_LLM_MODEL = "google/flan-t5-base"
DEFAULT_TOP_K = 5

# Resolve paths relative to project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
FAISS_INDEX_PATH = PROJECT_ROOT / "data" / "embeddings" / "faiss_index" / "pubmedqa_index_flatl2.faiss"
CHUNK_MAPPING_PATH = PROJECT_ROOT / "data" / "embeddings" / "faiss_index" / "chunk_mapping.pkl"


# ── RAG Pipeline Class ──────────────────────────────────────────────────────

class RAGPipeline:
    """
    Retrieval-Augmented Generation pipeline.

    Components:
    1. SentenceTransformer encoder (query embedding)
    2. FAISS index (vector retrieval)
    3. Chunk mapping (id → text)
    4. HuggingFace LLM (answer generation)
    """

    def __init__(
        self,
        embedding_model: str = DEFAULT_EMBEDDING_MODEL,
        llm_model: str = DEFAULT_LLM_MODEL,
        top_k: int = DEFAULT_TOP_K,
        faiss_index_path: str = None,
        chunk_mapping_path: str = None,
    ):
        self.top_k = top_k

        # ── Load embedding model ─────────────────────────────────────
        print(f"Loading embedding model: {embedding_model}")
        self.encoder = SentenceTransformer(embedding_model)

        # ── Load FAISS index ─────────────────────────────────────────
        idx_path = faiss_index_path or str(FAISS_INDEX_PATH)
        print(f"Loading FAISS index: {idx_path}")
        self.index = faiss.read_index(idx_path)
        print(f"  Vectors in index: {self.index.ntotal:,}")

        # ── Load chunk mapping ───────────────────────────────────────
        map_path = chunk_mapping_path or str(CHUNK_MAPPING_PATH)
        print(f"Loading chunk mapping: {map_path}")
        with open(map_path, "rb") as f:
            self.mapping_df = pickle.load(f)

        # ── Load LLM ────────────────────────────────────────────────
        print(f"Loading LLM: {llm_model}")
        self.generator = hf_pipeline(
            "text2text-generation",
            model=llm_model,
            max_new_tokens=256,
            do_sample=False,
        )
        print("✅ RAG Pipeline ready")

    def retrieve(self, query: str, top_k: int = None) -> list[dict]:
        """
        Embed query and retrieve top-k chunks from FAISS.

        Returns list of dicts with keys: chunk_id, question, context,
        answer, category, text_chunk, distance
        """
        k = top_k or self.top_k

        query_vector = self.encoder.encode(
            [query], convert_to_numpy=True
        ).astype(np.float32)

        D, I = self.index.search(query_vector, k)

        results = []
        for rank in range(k):
            idx = int(I[0, rank])
            dist = float(D[0, rank])
            row = self.mapping_df.iloc[idx]
            results.append({
                "chunk_id": idx,
                "question": row["question"],
                "context": row["context"],
                "answer": row["answer"],
                "category": row.get("category", "Unknown"),
                "text_chunk": row["text_chunk"],
                "distance": dist,
            })

        return results

    def retrieve_by_category(self, query: str, category: str, top_k: int = None) -> list[dict]:
        """
        Retrieve top-k chunks, then filter/boost results matching the given category.

        Strategy:
        1. Retrieve top_k * 3 candidates from FAISS
        2. Prioritise chunks matching the predicted category
        3. Return top_k results (category matches first, then others)
        """
        k = top_k or self.top_k
        search_k = min(k * 3, self.index.ntotal)  # retrieve more candidates

        query_vector = self.encoder.encode(
            [query], convert_to_numpy=True
        ).astype(np.float32)

        D, I = self.index.search(query_vector, search_k)

        # Build candidate list
        candidates = []
        for rank in range(search_k):
            idx = int(I[0, rank])
            dist = float(D[0, rank])
            row = self.mapping_df.iloc[idx]
            candidates.append({
                "chunk_id": idx,
                "question": row["question"],
                "context": row["context"],
                "answer": row["answer"],
                "category": row.get("category", "Unknown"),
                "text_chunk": row["text_chunk"],
                "distance": dist,
            })

        # Sort: category matches first (same distance order), then others
        matched = [c for c in candidates if c["category"] == category]
        unmatched = [c for c in candidates if c["category"] != category]

        results = (matched + unmatched)[:k]
        return results

    def answer_with_routing(self, query: str, category: str = None, top_k: int = None) -> dict:
        """
        Full pipeline with classifier routing:
        query → classify (external) → category-filtered retrieve → generate → disclaimer.

        If category is provided, retrieval is filtered by that category.
        If not, falls back to standard retrieval.
        """
        if category:
            retrieved = self.retrieve_by_category(query, category, top_k)
        else:
            retrieved = self.retrieve(query, top_k)

        raw_answer = self.generate(query, retrieved)

        sources = [
            {
                "chunk_id": r["chunk_id"],
                "question": r["question"],
                "category": r["category"],
                "distance": r["distance"],
            }
            for r in retrieved
        ]

        return {
            "question": query,
            "category": category or "Unknown",
            "answer": raw_answer + DISCLAIMER,
            "answer_raw": raw_answer,
            "retrieved_sources": sources,
            "disclaimer_present": True,
            "top_k": len(retrieved),
            "category_matched_sources": sum(1 for s in sources if s["category"] == category),
        }

    def generate(self, query: str, retrieved_chunks: list[dict]) -> str:
        """
        Build prompt from retrieved context and generate answer.
        """
        # Build context block from retrieved chunks
        context_parts = []
        for i, chunk in enumerate(retrieved_chunks, 1):
            context_parts.append(
                f"[Source {i}]\n"
                f"Question: {chunk['question']}\n"
                f"Context: {chunk['context'][:500]}\n"
                f"Answer: {chunk['answer']}"
            )
        context_block = "\n\n".join(context_parts)

        prompt = (
            f"You are a medical assistant. Answer the question based ONLY on "
            f"the provided context. If the context doesn't contain enough "
            f"information, say so.\n\n"
            f"Context:\n{context_block}\n\n"
            f"Question: {query}\n\n"
            f"Answer:"
        )

        output = self.generator(prompt)[0]["generated_text"]
        return output.strip()

    def answer(self, query: str, top_k: int = None) -> dict:
        """
        Full RAG pipeline: retrieve → generate → add disclaimer.

        Returns dict with: question, answer, answer_with_disclaimer,
        retrieved_sources, disclaimer_present
        """
        retrieved = self.retrieve(query, top_k)
        raw_answer = self.generate(query, retrieved)

        sources = [
            {
                "chunk_id": r["chunk_id"],
                "question": r["question"],
                "category": r["category"],
                "distance": r["distance"],
            }
            for r in retrieved
        ]

        return {
            "question": query,
            "answer": raw_answer + DISCLAIMER,
            "answer_raw": raw_answer,
            "retrieved_sources": sources,
            "disclaimer_present": True,
            "top_k": len(retrieved),
        }


# ── Module-level convenience functions ───────────────────────────────────────

_pipeline_instance = None


def build_rag_pipeline(**kwargs) -> RAGPipeline:
    """Build and cache a RAG pipeline instance."""
    global _pipeline_instance
    _pipeline_instance = RAGPipeline(**kwargs)
    return _pipeline_instance


def answer(query: str, pipeline: RAGPipeline = None, **kwargs) -> dict:
    """
    Answer a query using the RAG pipeline.
    Builds the pipeline on first call if not provided.
    """
    global _pipeline_instance
    if pipeline is None:
        if _pipeline_instance is None:
            _pipeline_instance = build_rag_pipeline()
        pipeline = _pipeline_instance
    return pipeline.answer(query, **kwargs)


def retrieve(query: str, pipeline: RAGPipeline = None, **kwargs) -> list[dict]:
    """Retrieve chunks for a query."""
    global _pipeline_instance
    if pipeline is None:
        if _pipeline_instance is None:
            _pipeline_instance = build_rag_pipeline()
        pipeline = _pipeline_instance
    return pipeline.retrieve(query, **kwargs)


